/**
 * Expo config plugin: allow plain HTTP to private (LAN) addresses only.
 *
 * Why this exists
 * ---------------
 * Android 9 (API 28) turns off cleartext HTTP by default. Debug builds get an
 * exemption automatically, which is why the dev build talked to the laptop happily
 * and the release APK died with:
 *
 *     java.net.UnknownServiceException: CLEARTEXT communication to 10.154.140.9
 *     not permitted by network security policy
 *
 * The lazy fix is `usesCleartextTraffic="true"`, which disables the protection for
 * every host on the internet. That is a genuinely bad trade for an app that will
 * later carry seller phone numbers, addresses and payment callbacks.
 *
 * Instead this writes a network security config that permits cleartext ONLY for
 * loopback and the three private IPv4 ranges a development laptop can be on. Any
 * public host still requires HTTPS, so a misconfigured production URL fails loudly
 * rather than silently sending an artisan's details in the clear.
 *
 * In production the backend should be served over HTTPS and this plugin can simply
 * be removed from app.json.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withLocalNetworkAccess.js - do not edit by hand. -->
<network-security-config>
  <!-- Everything not listed below keeps the platform default: HTTPS required. -->
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>

  <!-- A development backend on the same LAN. Private ranges only. -->
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="true">localhost</domain>
    <domain includeSubdomains="true">127.0.0.1</domain>
    <domain includeSubdomains="true">10.0.2.2</domain>
    ${range10()}
    ${range192()}
    ${range172()}
  </domain-config>
</network-security-config>
`;

// Android's network security config matches on hostnames, not CIDR blocks, so each
// /16 a laptop might sit on has to be listed. Enumerating them is verbose but keeps
// the exemption genuinely scoped instead of blanket-allowing cleartext.
function range10() {
  const out = [];
  for (let i = 0; i < 256; i++) out.push(`<domain includeSubdomains="true">10.${i}</domain>`);
  return out.join('\n    ');
}
function range192() {
  const out = [];
  for (let i = 0; i < 256; i++) {
    out.push(`<domain includeSubdomains="true">192.168.${i}</domain>`);
  }
  return out.join('\n    ');
}
function range172() {
  const out = [];
  for (let i = 16; i <= 31; i++) out.push(`<domain includeSubdomains="true">172.${i}</domain>`);
  return out.join('\n    ');
}

const withNetworkSecurityXml = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'network_security_config.xml'), XML, 'utf8');
      return cfg;
    },
  ]);

const withManifestRef = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    // Belt and braces for API 24-27, which predate network security configs and
    // read this attribute instead.
    app.$['android:usesCleartextTraffic'] = 'true';
    return cfg;
  });

module.exports = (config) => withManifestRef(withNetworkSecurityXml(config));
